export enum ReactionType {
	THUMBS_UP = "THUMBS_UP",
	GRINNING_FACE_WITH_BIG_EYES = "GRINNING_FACE_WITH_BIG_EYES",
	ASTONISHED_FACE = "ASTONISHED_FACE",
	FACE_WITH_TEARS_OF_JOY = "FACE_WITH_TEARS_OF_JOY",
	SMILING_FACE_WITH_HEART_EYES = "SMILING_FACE_WITH_HEART_EYES",
	HIGH_VOLTAGE = "HIGH_VOLTAGE"
}
