// This file is auto-generated by @hey-api/openapi-ts

export const NotificationSchema = {
	properties: {
		deviceToken: {
			type: "string"
		},
		notificationId: {
			type: "string"
		}
	},
	required: ["deviceToken", "notificationId"],
	type: "object",
	additionalProperties: false
} as const;

export const MomentSchema = {
	properties: {
		id: {
			type: "string"
		},
		date: {
			type: "integer",
			format: "date-time"
		},
		time: {
			type: "object",
			properties: {
				EU: {
					type: "integer",
					format: "date-time"
				},
				US: {
					type: "integer",
					format: "date-time"
				},
				WA: {
					type: "integer",
					format: "date-time"
				},
				EA: {
					type: "integer",
					format: "date-time"
				}
			},
			required: ["EU", "US", "WA", "EA"]
		}
	},
	required: ["id", "date", "time"],
	type: "object",
	additionalProperties: false
} as const;
