// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch";
import type {
	SendNotificationsData,
	SendNotificationsError,
	SendNotificationsResponse
} from "./types.gen";

export const client = createClient(createConfig());

export const sendNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<SendNotificationsData, ThrowOnError>
) => {
	return (options?.client ?? client).post<
		SendNotificationsResponse,
		SendNotificationsError,
		ThrowOnError
	>({
		...options,
		url: "/v1/send"
	});
};
