// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "@hey-api/client-fetch";
import type {
	SendNotificationsData,
	SendNotificationsError,
	SendNotificationsResponse,
	CheckAuthError,
	CheckAuthResponse,
	GetMomentsData,
	GetMomentsError,
	GetMomentsResponse
} from "./types.gen";

export const client = createClient(createConfig());

export const sendNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<SendNotificationsData, ThrowOnError>
) => {
	return (options?.client ?? client).post<
		SendNotificationsResponse,
		SendNotificationsError,
		ThrowOnError
	>({
		...options,
		url: "/v1/notifications"
	});
};

export const checkAuth = <ThrowOnError extends boolean = false>(
	options?: Options<unknown, ThrowOnError>
) => {
	return (options?.client ?? client).get<CheckAuthResponse, CheckAuthError, ThrowOnError>({
		...options,
		url: "/v1/auth/check"
	});
};

export const getMoments = <ThrowOnError extends boolean = false>(
	options?: Options<GetMomentsData, ThrowOnError>
) => {
	return (options?.client ?? client).get<GetMomentsResponse, GetMomentsError, ThrowOnError>({
		...options,
		url: "/v1/moments"
	});
};
