// This file is auto-generated by @hey-api/openapi-ts

export type Notification = {
	deviceToken: string;
	notificationId: string;
};

export type SendNotificationsData = {
	body?: {
		notifications?: Array<Notification>;
	};
};

export type SendNotificationsResponse = {
	success?: boolean;
};

export type SendNotificationsError = unknown;
