// This file is auto-generated by @hey-api/openapi-ts

export type Notification = {
	deviceToken: string;
	notificationId: string;
};

export type Moment = {
	id: string;
	date: number;
	time: {
		EU: number;
		US: number;
		WA: number;
		EA: number;
	};
};

export type SendNotificationsData = {
	body?: {
		notifications?: Array<Notification>;
	};
};

export type SendNotificationsResponse = {
	success?: boolean;
};

export type SendNotificationsError = {
	error?: string;
};

export type CheckAuthResponse = {
	success?: boolean;
};

export type CheckAuthError = {
	error?: string;
};

export type GetMomentsData = {
	query?: {
		/**
		 * Return moments after this timestamp
		 */
		after?: number;
		/**
		 * Limit the number of moments to return
		 */
		limit?: number;
	};
};

export type GetMomentsResponse = {
	moments?: Array<Moment>;
};

export type GetMomentsError = {
	error?: string;
};
